client/README.md, client/integrations/standalone/src/index.tsx, client/integrations/standalone/src/url-helper.ts
- server: for server
- pid: for pid
=> Add parameters for standalone integration

client/integrations/standalone/tests/combobox-util.ts, client/integrations/standalone/tests/dialog-start.spec.ts, client/integrations/standalone/tests/message.spec.ts, client/integrations/standalone/tests/tab-state.spec.ts, client/packages/core/src/validation/validation-mock.ts, client/packages/editor/src/App.css, client/packages/editor/src/components/editors/InscriptionEditor.css, client/packages/editor/src/components/editors/InscriptionEditor.tsx, client/packages/editor/src/components/props/message.ts, client/packages/editor/src/components/props/tab.ts, client/packages/editor/src/components/tabs/CallTab.tsx, client/packages/editor/src/components/tabs/NameTab.tsx, client/packages/editor/src/components/widgets/IvyIcon.tsx, client/packages/editor/src/components/widgets/label/LabelInput.css, client/packages/editor/src/components/widgets/label/LabelInput.tsx, client/packages/editor/src/context/useValidation.ts
=> Fix tab validations

client/packages/editor/src/App.tsx, client/packages/editor/src/components/tabs/TaskTab.tsx, client/packages/editor/src/components/widgets/checkbox/Checkbox.test.tsx, client/packages/editor/src/components/widgets/combobox/Combobox.test.tsx, client/packages/editor/src/components/widgets/select/PrioritySelect.test.tsx, client/packages/editor/src/components/widgets/select/PrioritySelect.tsx, client/packages/editor/src/components/widgets/select/ResponsibleSelect.test.tsx, client/packages/editor/src/components/widgets/select/Select.test.tsx, client/packages/editor/src/components/widgets/select/Select.tsx, client/packages/editor/src/components/widgets/table/CustomFieldTable.test.tsx, client/packages/editor/src/components/widgets/table/DocumentTable.test.tsx, client/packages/editor/src/components/widgets/table/MappingTree.test.tsx, client/packages/editor/src/components/widgets/table/table.test-helper.tsx, client/packages/editor/src/components/widgets/tag/Tags.test.tsx, client/packages/editor/src/context/useEditorContext.ts, client/packages/editor/tsconfig.json
- Add tests for Checkbox
- Add tests for Select (also PrioritySelect and ResponsibleSelect)
- Add tests for CustomFieldTable
=> XIVY-10351 Improve Task Tab

client/packages/editor/src/components/widgets/code-editor/CodeEditor.css, client/packages/editor/src/components/widgets/code-editor/CodeEditor.tsx
=> Fix code editor resize

client/packages/core/src/data/inscription-data.ts, client/packages/core/src/data/name-data.ts, client/packages/core/src/inscription-client.ts, client/packages/core/src/inscription-protocol.ts, client/packages/core/src/meta/inscription-meta.ts, client/packages/core/src/validation/validation-mock.ts, client/packages/editor/src/components/widgets/select/ResponsibleSelect.css, client/packages/editor/src/components/widgets/select/ResponsibleSelect.test.tsx, client/packages/editor/src/components/widgets/select/ResponsibleSelect.tsx, client/packages/editor/src/components/widgets/select/Select.tsx
- Change meta method of dialog starts
- Add meta for roles
=> XIVY-10351 Meta changes

integrations/standalone/tests/dialog-start.spec.ts, packages/core/src/inscription-client-jsonrpc.ts, packages/core/src/mock/data/data-mock.ts, packages/core/src/mock/inscription-client-mock.ts, packages/core/src/mock/meta/meta-mock.ts, packages/editor/src/components/editors/activity/workflow.tsx, packages/editor/src/components/tabs/call/CallTab.tsx, packages/editor/src/components/tabs/call/MappingTreeWithCode.tsx, packages/editor/src/components/tabs/call/useCallData.ts, packages/editor/src/components/tabs/output/OutputTab.tsx, packages/editor/src/components/tabs/output/useOutputData.ts, packages/editor/src/components/tabs/task/error/ErrorSelect.tsx, packages/editor/src/components/tabs/task/priority/PrioritySelect.tsx, packages/editor/src/components/tabs/task/responsible/ResponsibleSelect.tsx, packages/editor/src/components/widgets/table/MappingTree.test.tsx, packages/editor/src/components/widgets/table/MappingTree.tsx, packages/editor/src/components/widgets/table/cell/ExpandableCell.css, packages/editor/src/components/widgets/table/cell/ExpandableCell.tsx, packages/editor/src/components/widgets/table/header/TableHeader.css, packages/editor/src/components/widgets/table/header/TableHeader.tsx, packages/editor/src/components/widgets/table/mapping-tree-data.test.ts, packages/editor/src/components/widgets/table/mapping-tree-data.ts, packages/protocol/src/data/call-data.ts, packages/protocol/src/data/common.ts, packages/protocol/src/data/output-data.ts, packages/protocol/src/inscription-client.ts, packages/protocol/src/inscription-protocol.ts, packages/protocol/src/meta/inscription-meta.ts
- Adapt MappingInfo meta data changes
- Add OutputTab
- Add meta/out/map meta request
- Improve MappingTree widget
- Load nodes lazy
- Show unknown mappings
- Add more tests
=>  XIVY-10509 Adapt mapping info meta changes

packages/core/src/mock/validation/validation-mock.ts, packages/editor/src/App.tsx, packages/editor/src/utils/remove-defaults.test.ts, packages/editor/src/utils/remove-defaults.ts
- Needed until all elements provide default data
=> Remove default values before save back

packages/editor/src/components/tabs/task/TaskTab.test.tsx, packages/editor/src/components/tabs/task/TaskTab.tsx
=> XIVY-10872 Support no task if no output

integrations/standalone/tests/engine/events/end.spec.ts, integrations/standalone/tests/engine/events/intermediate.spec.ts, integrations/standalone/tests/engine/gateways/gateway.spec.ts, integrations/standalone/tests/engine/tabs/end-page-tab.ts, packages/editor/src/components/editors/event/end.tsx, packages/editor/src/components/tabs/EndPageTab.tsx, packages/editor/src/components/tabs/call/dialog/DialogCallTab.test.tsx, packages/editor/src/components/tabs/call/sub/SubCallTab.test.tsx, packages/editor/src/components/tabs/call/trigger/TriggerCallTab.test.tsx, packages/editor/src/components/tabs/case/CaseTab.test.tsx, packages/editor/src/components/tabs/end-page/EndPageTab.test.tsx, packages/editor/src/components/tabs/end-page/EndPageTab.tsx, packages/editor/src/components/tabs/end-page/useEndPageData.ts, packages/editor/src/components/tabs/index.ts, packages/editor/src/components/tabs/name/NameTab.test.tsx, packages/editor/src/components/tabs/output/CodeTab.test.tsx, packages/editor/src/components/tabs/output/OutputTab.test.tsx, packages/editor/src/components/tabs/task/TaskTab.test.tsx, packages/editor/src/components/tabs/task/TasksTab.test.tsx, packages/editor/src/components/tabs/task/expiry/ExpiryPart.test.tsx, packages/editor/src/components/tabs/task/general/TaskPart.test.tsx, packages/editor/src/components/tabs/task/options/PersistPart.test.tsx, packages/editor/src/components/tabs/task/options/TaskListPart.test.tsx, packages/editor/src/test-utils/test-utils.tsx, packages/protocol/src/data/end-page-data.ts, packages/protocol/src/data/index.ts, packages/protocol/src/data/inscription-data.ts
=> Add EndPageTab

build/unpublish-npm.sh
./unpublish-npm.sh versionParam
Unpublishes the given version from the npm registry.
=> Add an unpublish script

integrations/standalone/src/mock/inscription-client-mock.ts, packages/editor/src/context/useEditorContext.ts, packages/protocol/src/data/inscription.ts
should get green, once the core change is merged: https://github.com/axonivy/core/pull/2661
=> adapt thirdparty impl.schema

integrations/standalone/tests/integration/project/.settings/ch.ivyteam.ivy.designer.prefs, integrations/standalone/tests/screenshots/project/.settings/ch.ivyteam.ivy.designer.prefs
Raise ivy projects to latest version
=> Raise ivy projects to latest version

integrations/standalone/package.json, integrations/standalone/pom.xml, integrations/standalone/tests/screenshots/pom.xml, integrations/standalone/tests/screenshots/project/pom.xml, lerna.json, packages/core/package.json, packages/editor/package.json, packages/icons/package.json, packages/protocol/package.json
Raise version to 11.2.0-SNAPSHOT
=> Raise version to 11.2.0-SNAPSHOT

.ivy/raise-build-plugin-version.sh, integrations/standalone/tests/integration/project/pom.xml, integrations/standalone/tests/screenshots/project/pom.xml
Raising project-build-plugin version to 11.1.0 / 11.1.1-SNAPSHOT
=> Raising project-build-plugin version to 11.1.0 / 11.1.1-SNAPSHOT

integrations/standalone/src/mock/validation-mock.ts, packages/editor/src/App.tsx, packages/editor/src/components/tabs/output/CodeTab.test.tsx, packages/editor/src/components/tabs/output/OutputTab.test.tsx, packages/editor/src/components/tabs/output/useOutputData.ts, packages/editor/src/context/useDataContext.ts, packages/editor/src/test-utils/test-utils.tsx, packages/protocol/src/data/index.ts, packages/protocol/src/data/inscription-data.ts, packages/protocol/src/data/inscription-type.ts, packages/protocol/src/data/tab-data.ts, packages/protocol/src/defaults/common-defaults.ts
- Rename DataBeta to ElementData
- Use OutputData instead of ElementScript type
=> XIVY-11279 Cleanup and Refactoring

build/Jenkinsfile, packages/editor/src/components/editors/InscriptionEditor.css, packages/editor/src/components/editors/InscriptionEditor.tsx, packages/editor/src/components/parts/name/NamePart.tsx, packages/editor/src/components/props/part.ts, packages/editor/src/components/widgets/accordion/Accordion.css, packages/editor/src/components/widgets/accordion/Accordion.test.tsx, packages/editor/src/components/widgets/accordion/Accordion.tsx, packages/editor/src/components/widgets/fieldset/SummaryFieldset.css, packages/editor/src/components/widgets/fieldset/SummaryFieldset.test.tsx, packages/editor/src/components/widgets/fieldset/SummaryFieldset.tsx, packages/editor/src/components/widgets/fieldset/index.ts, packages/editor/src/components/widgets/tag/SummaryTags.tsx, packages/editor/src/components/widgets/tag/Tags.css, packages/editor/src/components/widgets/tag/index.ts
=> XIVY-11279 Add summary part

packages/editor/src/components/editors/InscriptionEditor.tsx, packages/editor/src/components/parts/condition/ConditionTable.test.tsx, packages/editor/src/components/parts/condition/ConditionTable.tsx, packages/editor/src/components/parts/condition/condition.test.ts, packages/editor/src/components/parts/condition/condition.ts, packages/editor/src/components/widgets/index.ts, packages/editor/src/components/widgets/table/cell/CodeEditorCell.css, packages/editor/src/components/widgets/table/cell/CodeEditorCell.tsx
=> XIVY-11447 Remove button for unknown conditions

packages/editor/src/components/parts/condition/ConditionTable.tsx
=> XIVY-11447 conditions location

packages/editor/src/components/parts/condition/ConditionTable.tsx
=> enforce boolean return type

integrations/standalone/src/mock/inscription-client-mock.ts, integrations/standalone/src/mock/meta-mock.ts, packages/core/src/inscription-client-jsonrpc.ts, packages/editor/src/components/parts/call/CallSelect.test.tsx, packages/editor/src/components/parts/call/CallSelect.tsx, packages/editor/src/components/parts/call/dialog/new-html-dialog-action.ts, packages/editor/src/components/parts/common/mapping-tree/MappingTree.test.tsx, packages/editor/src/components/parts/common/mapping-tree/MappingTree.tsx, packages/editor/src/components/parts/common/mapping-tree/mapping-tree-data.test.ts, packages/editor/src/components/parts/common/mapping-tree/mapping-tree-data.ts, packages/editor/src/components/parts/common/parameter/ParameterTable.test.tsx, packages/editor/src/components/widgets/combobox/Combobox.tsx, packages/editor/src/components/widgets/fieldset/Fieldset.tsx, packages/editor/src/components/widgets/table/cell/ExpandableCell.tsx, packages/protocol/src/data/action.ts, packages/protocol/src/data/index.ts, packages/protocol/src/data/inscription.ts, packages/protocol/src/inscription-client.ts, packages/protocol/src/inscription-protocol.ts
- Add deprecation to CallableStart obj
- Add description to Variable meta
Deprecation on CallSelect:
Description on MappingTree:
=> XIVY-10873 Add more info for mapping meta

packages/editor/src/components/editors/event/start.tsx, packages/editor/src/components/parts/start/StartPart.tsx, packages/editor/src/components/parts/start/useNameSyncher.test.tsx, packages/editor/src/components/parts/start/useNameSyncher.ts
=> XIVY-10873 Add signature to name syncher

integrations/standalone/src/mock/inscription-client-mock.ts, integrations/standalone/src/mock/meta-mock.ts, integrations/standalone/tests/integration/gateways/gateway.spec.ts, packages/core/src/inscription-client-jsonrpc.ts, packages/editor/src/components/editors/event/call-sub.tsx, packages/editor/src/components/editors/event/html-dialog.tsx, packages/editor/src/components/editors/event/webservice.tsx, packages/editor/src/components/editors/gateway/all-gateway-editors.tsx, packages/editor/src/components/parts/ResultPart.tsx, packages/editor/src/components/parts/index.ts, packages/editor/src/components/parts/result/ResultPart.test.tsx, packages/editor/src/components/parts/result/ResultPart.tsx, packages/editor/src/components/parts/result/useResultData.ts, packages/editor/src/test-utils/test-utils.tsx, packages/protocol/src/data/inscription-data.ts, packages/protocol/src/data/part-data.ts, packages/protocol/src/defaults/common-defaults.ts, packages/protocol/src/inscription-client.ts, packages/protocol/src/inscription-protocol.ts
- Add result part to Sub Start, WS start, Hd init and Hd method
- Add output (with multiple outs) to split
=> XIVY-10873 Add result page

build/Jenkinsfile, build/integration/Jenkinsfile, build/playwright/Dockerfile, build/screenshots/Jenkinsfile, integrations/standalone/package.json, integrations/standalone/playwright.config.ts, integrations/standalone/tests/customReporter.ts, yarn.lock
- Remove AttachmentPublisher (not working with updated xml report)
=> Update playwright to 1.34.3

integrations/standalone/tests/integration/events/start.spec.ts, integrations/standalone/tests/integration/parts/name.ts, integrations/standalone/tests/integration/parts/result.ts, integrations/standalone/tests/integration/project/src_hd/screenshot/project/exampleHtmlDialog/exampleHtmlDialogProcess.p.json, packages/editor/src/components/parts/common/customfield/CustomFieldTable.test.tsx, packages/editor/src/components/parts/common/customfield/CustomFieldTable.tsx, packages/editor/src/components/parts/name/NamePart.test.tsx, packages/editor/src/components/parts/name/NamePart.tsx, packages/editor/src/components/parts/name/document/DocumentTable.test.tsx, packages/editor/src/components/parts/name/document/DocumentTable.tsx, packages/editor/src/components/parts/result/ResultPart.test.tsx, packages/editor/src/components/parts/result/ResultPart.tsx, packages/editor/src/components/parts/start/StartPart.test.tsx, packages/editor/src/components/parts/start/StartPart.tsx, packages/editor/src/components/widgets/collapsible/CollapsiblePart.css, packages/editor/src/test-utils/collapsible-utils.tsx
- Name: means / docs table in collapsable
- Result: params table in collapsable
- Input: params table in collapsable
- Remove "Action" header text from tables
=> XIVY-10873 UI feedback from bb

packages/editor/src/components/editors/menu/HeaderMenu.css, packages/editor/src/components/editors/menu/HeaderMenu.tsx
- Rename light / dark mode item to "Switch Theme"
- Add cursor styles
=> Fix small findings in theader menu by bb

inscription-editor.code-workspace, integrations/standalone/tests/integration/activites/interface.spec.ts, integrations/standalone/tests/integration/parts/mail-header.ts, packages/editor/src/components/editors/activity/interface.tsx, packages/editor/src/components/parts/index.ts, packages/editor/src/components/parts/mail/MailHeaderPart.test.tsx, packages/editor/src/components/parts/mail/MailHeaderPart.tsx, packages/editor/src/components/parts/mail/useMailHeaderData.ts, packages/protocol/src/data/inscription-data.ts, packages/protocol/src/data/part-data.ts, packages/protocol/src/defaults/common-defaults.ts
Solution from me, currently without any tests
=> Email header part

integrations/standalone/tests/mock/browser.spec.ts, integrations/standalone/tests/mock/dnd.spec.ts, packages/editor/src/components/browser/Browser.tsx
- re enable dnd test for webkit
=> XIVY-11598 Add mock test for attribute browser

package.json
=> XIVY-11415 fix publish next version

integrations/standalone/tests/mock/browser.spec.ts, packages/editor/src/App.css, packages/editor/src/components/browser/AttributeBrowser.tsx, packages/editor/src/components/browser/Browser.css, packages/editor/src/components/browser/Browser.tsx, packages/editor/src/components/browser/CmsBrowser.tsx, packages/editor/src/components/browser/index.ts, packages/editor/src/components/browser/useBrowser.ts, packages/editor/src/components/editors/menu/HeaderMenu.css, packages/editor/src/components/parts/common/mapping-tree/MappingTree.tsx, packages/editor/src/components/parts/task/MultiTasksPart.tsx, packages/editor/src/components/widgets/code-editor/CodeEditor.css, packages/editor/src/components/widgets/code-editor/MacroArea.tsx, packages/editor/src/components/widgets/code-editor/MacroInput.tsx, packages/editor/src/components/widgets/code-editor/ScriptArea.tsx, packages/editor/src/components/widgets/code-editor/ScriptInput.tsx, packages/editor/src/components/widgets/combobox/Combobox.css, packages/editor/src/components/widgets/input/IconInput.css, packages/editor/src/components/widgets/input/IconInput.tsx, packages/editor/src/components/widgets/input/Input.css, packages/editor/src/components/widgets/popover/Popover.css, packages/editor/src/components/widgets/select/Select.css, packages/editor/src/components/widgets/tab/Tab.css, packages/editor/src/components/widgets/tab/Tab.test.tsx, packages/editor/src/components/widgets/tab/Tab.tsx, packages/editor/src/components/widgets/table/index.ts, packages/editor/src/components/widgets/table/row/SelectRow.css, packages/editor/src/components/widgets/table/row/SelectRow.tsx, packages/editor/src/components/widgets/table/table/Table.css, packages/editor/src/components/widgets/table/table/Table.tsx
- Add attribute browser
- Add proto cms browser
- Improve style of browser
https://github.com/axonivy/inscription-client/assets/42733123/56f49570-c9d9-4d95-bd39-094c2246ecd3
=> XIVY-11598 Attribute browser

packages/editor/src/components/parts/task/expiry/ExpiryPart.tsx, packages/editor/src/components/widgets/code-editor/CodeEditor.tsx, packages/editor/src/components/widgets/code-editor/MacroInput.tsx, packages/editor/src/components/widgets/code-editor/ResizableCodeEditor.tsx, packages/editor/src/components/widgets/code-editor/ScriptInput.tsx, packages/editor/src/components/widgets/table/cell/ScriptCell.tsx
- Create context prop for ScriptInput with location and type. (This fixes the condition attribute browser, because it no longer sends the request with the type in the location)
=> XIVY-11598 Fix script location

integrations/standalone/src/mock/inscription-client-mock.ts, packages/core/src/inscription-client-jsonrpc.ts, packages/editor/src/App.tsx, packages/editor/src/components/editors/InscriptionEditor.css, packages/protocol/src/inscription-client.ts, packages/protocol/src/inscription-protocol.ts
- Trigger validation request at start
- Set max-height to header messages
=> XIVY-11485 Improve validation

packages/editor/src/components/parts/case/CasePart.tsx, packages/editor/src/components/parts/common/customfield/CustomFieldPart.test.tsx, packages/editor/src/components/parts/common/customfield/CustomFieldPart.tsx, packages/editor/src/components/parts/common/customfield/CustomFieldTable.test.tsx, packages/editor/src/components/parts/common/customfield/CustomFieldTable.tsx, packages/editor/src/components/parts/end-page/EndPagePart.tsx, packages/editor/src/components/parts/name/document/DocumentTable.tsx, packages/editor/src/components/parts/task/task/TaskPart.tsx, packages/editor/src/components/widgets/table/cell/SelectCell.css, packages/protocol/src/actions.ts
- Open custom-field config
- Open document
=> XIVY-11521 Add more open actions

packages/editor/src/components/parts/name/useNameSyncher.ts
- Do not trigger endless save cyrcles
=> Fix name syncher

packages/editor/src/App.css, packages/editor/src/components/widgets/checkbox/Checkbox.css, packages/editor/src/components/widgets/code-editor/CodeEditor.css, packages/editor/src/components/widgets/code-editor/CodeEditor.tsx, packages/editor/src/components/widgets/fieldset/Fieldset.css, packages/editor/src/components/widgets/fieldset/Fieldset.tsx, packages/editor/src/components/widgets/input/Input.css, packages/editor/src/components/widgets/select/Select.css
Style fieldset input when error or warning message is present
=> XIVY-11485 Style fieldset input when message

packages/editor/src/App.css, packages/editor/src/components/browser/AttributeBrowser.tsx, packages/editor/src/components/parts/call/CallMapping.tsx, packages/editor/src/components/parts/call/dialog/DialogCallPart.tsx, packages/editor/src/components/parts/call/sub/SubCallPart.tsx, packages/editor/src/components/parts/call/trigger/TriggerCallPart.tsx, packages/editor/src/components/parts/case/CasePart.tsx, packages/editor/src/components/parts/common/mapping-tree/MappingPart.test.tsx, packages/editor/src/components/parts/common/mapping-tree/MappingPart.tsx, packages/editor/src/components/parts/common/mapping-tree/MappingTree.tsx, packages/editor/src/components/parts/common/mapping-tree/useMappingTree.ts, packages/editor/src/components/parts/condition/ConditionPart.tsx, packages/editor/src/components/parts/end-page/EndPagePart.tsx, packages/editor/src/components/parts/error/ErrorCatchPart.tsx, packages/editor/src/components/parts/mail/MailHeaderPart.tsx, packages/editor/src/components/parts/output/CodePart.tsx, packages/editor/src/components/parts/output/OutputPart.tsx, packages/editor/src/components/parts/result/ResultPart.tsx, packages/editor/src/components/parts/signal/SignalCatchPart.tsx, packages/editor/src/components/parts/start/StartPart.tsx, packages/editor/src/components/parts/task/MultiTasksPart.tsx, packages/editor/src/components/parts/task/SingleTaskPart.tsx, packages/editor/src/components/widgets/table/index.ts, packages/editor/src/components/widgets/table/row/ValidationRow.css, packages/editor/src/components/widgets/table/row/ValidationRow.tsx, packages/editor/src/components/widgets/table/table/Table.css, packages/editor/src/context/usePath.tsx, packages/editor/src/context/useValidation.ts
=> XIVY-11485 Add mapping tree validation

integrations/standalone/tests/integration/parts/task.ts, integrations/standalone/tests/pageobjects/CodeEditor.ts, integrations/standalone/tests/pageobjects/ResponsibleSelect.ts, packages/editor/src/components/parts/common/customfield/CustomFieldPart.tsx, packages/editor/src/components/parts/common/customfield/CustomFieldTable.tsx, packages/editor/src/components/parts/common/mapping-tree/MappingTree.tsx, packages/editor/src/components/parts/common/parameter/ParameterTable.tsx, packages/editor/src/components/parts/mail/MailAttachmentPart.tsx, packages/editor/src/components/parts/start/StartPart.tsx, packages/editor/src/components/parts/task/options/TaskListPart.tsx, packages/editor/src/components/parts/task/priority/PrioritySelect.css, packages/editor/src/components/parts/task/priority/PrioritySelect.tsx, packages/editor/src/components/parts/task/responsible/ResponsibleSelect.css, packages/editor/src/components/parts/task/responsible/ResponsibleSelect.tsx, packages/editor/src/components/parts/task/task/TaskPart.test.tsx, packages/editor/src/components/parts/task/task/TaskPart.tsx, packages/editor/src/components/widgets/fieldset/Fieldset.test.tsx, packages/editor/src/components/widgets/fieldset/Fieldset.tsx, packages/editor/src/components/widgets/fieldset/useFieldset.test.tsx, packages/editor/src/components/widgets/table/row/ValidationRow.test.tsx, packages/editor/src/components/widgets/table/row/ValidationRow.tsx, packages/editor/src/context/usePath.test.tsx, packages/editor/src/context/usePath.tsx, packages/editor/src/test-utils/setupTests.tsx, packages/protocol/src/data/inscription-data.ts
- Change attachment json path
- Fix input params validations
- Show validations of CustomField
- Add validations to task
=> XIVY-11485 Add more validations

integrations/standalone/tests/pageobjects/Table.ts, packages/editor/src/components/parts/common/path/validation/ValidationRow.test.tsx, packages/editor/src/components/widgets/table/row/MessageRow.css, packages/editor/src/components/widgets/table/row/MessageRow.test.tsx, packages/editor/src/components/widgets/table/row/MessageRow.tsx
=> XIVY-11485 Show message on ValidationRow

integrations/standalone/tests/integration/parts/condition.ts, integrations/standalone/tests/integration/parts/mail-attachments.ts, integrations/standalone/tests/integration/parts/name.ts, integrations/standalone/tests/integration/parts/task.ts, integrations/standalone/tests/mock/code-editor-input.spec.ts, integrations/standalone/tests/pageobjects/Composite.ts, integrations/standalone/tests/pageobjects/Popover.ts, integrations/standalone/tests/pageobjects/Table.ts, packages/editor/src/components/parts/condition/ConditionPart.tsx
Imrpove also the task part test with a dedicated Task page object
=> Use new page obejcts in the condtion part test

integrations/standalone/src/mock/inscription-client-mock.ts, packages/core/src/inscription-client-jsonrpc.ts, packages/editor/src/components/browser/AttributeBrowser.tsx, packages/editor/src/components/parts/call/dialog/DialogCallPart.tsx, packages/editor/src/components/parts/call/sub/SubCallPart.tsx, packages/editor/src/components/parts/call/trigger/TriggerCallPart.tsx, packages/editor/src/components/parts/common/exception-handler/ExceptionSelect.tsx, packages/editor/src/components/parts/condition/ConditionPart.tsx, packages/editor/src/components/parts/error/ErrorCatchPart.tsx, packages/editor/src/components/parts/output/OutputPart.tsx, packages/editor/src/components/parts/result/ResultPart.test.tsx, packages/editor/src/components/parts/result/ResultPart.tsx, packages/editor/src/components/parts/signal/SignalCatchPart.tsx, packages/editor/src/components/parts/start/StartPart.tsx, packages/editor/src/components/parts/task/responsible/ResponsibleSelect.tsx, packages/editor/src/components/widgets/combobox/Combobox.tsx, packages/editor/src/context/index.ts, packages/editor/src/context/useMeta.ts, packages/editor/src/test-utils/test-utils.tsx, packages/protocol/src/inscription-client.ts, packages/protocol/src/inscription-protocol.ts
Simplify inscription client api, by reduce all meta methods to one with a custom useMeta hook.
=> Add useMeta hook

integrations/standalone/tests/pageobjects/Composite.ts, integrations/standalone/tests/screenshots/activities/interface.spec.ts, integrations/standalone/tests/screenshots/activities/workflow.spec.ts, integrations/standalone/tests/screenshots/events/boundary.spec.ts, integrations/standalone/tests/screenshots/events/end.spec.ts, integrations/standalone/tests/screenshots/events/start.spec.ts, integrations/standalone/tests/screenshots/gateways/gateways.spec.ts, integrations/standalone/tests/screenshots/utils/screenshot-util.ts, integrations/standalone/tests/utils/accordion-util.ts, integrations/standalone/tests/utils/engine-util.ts
- Enable some screenshot tests
- Use pageobjects for screenshot tests
- Remove some utils
- Screenshot only accordion instead of full page
=> Screenshots

integrations/standalone/tests/integration/events/intermediate.spec.ts, integrations/standalone/tests/integration/events/start.spec.ts, integrations/standalone/tests/integration/parts/request.ts, integrations/standalone/tests/integration/parts/task.ts, integrations/standalone/tests/integration/parts/trigger.ts, integrations/standalone/tests/integration/project/processes/AllElements/MinimalInscription/Activity.p.json, integrations/standalone/tests/integration/project/processes/AllElements/MinimalInscription/EventAndGateway.p.json, integrations/standalone/tests/pageobjects/Composite.ts, integrations/standalone/tests/pageobjects/ResponsibleSelect.ts, integrations/standalone/tests/pageobjects/Select.ts, packages/editor/src/components/parts/common/responsible/RoleSelect.tsx, packages/editor/src/components/parts/request/RequestPart.tsx, packages/editor/src/components/parts/task/SingleTaskPart.test.tsx, packages/editor/src/components/parts/task/SingleTaskPart.tsx, packages/editor/src/components/parts/task/options/PersistPart.test.tsx, packages/editor/src/components/parts/task/options/PersistPart.tsx, packages/editor/src/components/parts/task/options/useTaskOptionsData.ts, packages/editor/src/components/parts/trigger/TriggerPart.test.tsx, packages/editor/src/components/parts/trigger/TriggerPart.tsx, packages/editor/src/components/widgets/checkbox/Checkbox.test.tsx, packages/editor/src/components/widgets/checkbox/Checkbox.tsx, packages/protocol/src/data/part-data.ts, packages/protocol/src/data/workflow-data.ts, packages/protocol/src/defaults/workflow-defaults.ts
Fix persist on start flag:
- Wrong config key
- Disabled if anonymous start is allowed
Add integration tests for request start:
- Request
- Trigger
- Task
- Case
=> XIVY-11703 Add start integration tests

packages/editor/src/components/parts/common/mapping-tree/MappingPart.test.tsx, packages/editor/src/components/parts/common/mapping-tree/MappingPart.tsx, packages/editor/src/components/parts/common/mapping-tree/mapping-tree-data.ts, packages/editor/src/components/parts/trigger/TriggerPart.test.tsx, packages/protocol/src/data/inscription-data.ts, packages/protocol/src/data/part-data.ts, packages/protocol/src/defaults/common-defaults.ts, packages/protocol/src/utils/type-helper.ts
This change has the effect, that more types are generated out of the inscription schema from the core.
=> Use more types form the inscription schema 🧙🏼‍♂️

packages/editor/src/components/parts/common/path/validation/ValidationRow.tsx, packages/editor/src/components/parts/condition/ConditionTable.tsx, packages/editor/src/components/parts/task/MultiTasksPart.test.tsx, packages/editor/src/components/parts/task/MultiTasksPart.tsx, packages/editor/src/components/parts/task/SingleTaskPart.tsx, packages/editor/src/components/parts/task/task/TaskPart.tsx, packages/editor/src/components/widgets/tab/Tab.css, packages/editor/src/components/widgets/tab/Tab.test.tsx, packages/editor/src/components/widgets/tab/Tab.tsx, packages/editor/src/components/widgets/table/row/MessageRow.tsx, packages/editor/src/components/widgets/table/row/ReorderRow.test.tsx, packages/editor/src/components/widgets/table/row/ReorderRow.tsx, packages/editor/src/context/usePath.tsx
- Tasks with indexd path
- Show message state on tasks tab
- Add ValidationReorderRow
=> XIVY-11945 Add more validation

.vscode/tasks.json, integrations/standalone/package.json, packages/icons/package.json, yarn.lock
- Downgrade fantasticon to v1.2.3: v2.0.0 uses newer version of glob, which causes path problems under windows
- Add mock start for windows
=> Fix windows environment

packages/editor/src/components/parts/error/useErrorThrowData.test.ts, packages/editor/src/components/parts/error/useErrorThrowData.ts
Feedback of bb: Error End display name should update to the current error code (if was the same)
=> XIVY-11710 Synch name of error end with error

build/integration/Jenkinsfile, integrations/standalone/playwright.config.ts
Run integration tests on branch only with chrome and on master/release branch with all browsers
=> Speed up integration tests on branch

packages/editor/src/components/parts/query/database/TableFields.test.tsx, packages/editor/src/components/parts/query/database/TableFields.tsx
=> XIVY-11711 Show unknown columns in fields table

integrations/standalone/tests/integration/events/start/ws.spec.ts, integrations/standalone/tests/integration/parts/web-service.ts, packages/editor/src/components/editors/event/webservice.tsx, packages/editor/src/components/parts/web-service/Exception.test.tsx, packages/editor/src/components/parts/web-service/Exception.tsx, packages/editor/src/components/parts/web-service/Permission.test.tsx, packages/editor/src/components/parts/web-service/Permission.tsx, packages/editor/src/components/parts/web-service/WebServicePart.test.tsx, packages/editor/src/components/parts/web-service/WebServicePart.tsx, packages/editor/src/components/parts/web-service/useWebServiceData.ts, packages/protocol/src/data/inscription-data.ts, packages/protocol/src/data/part-data.ts, packages/protocol/src/defaults/common-defaults.ts
- added type WebserviceStartData to part-data.ts
- added useWebServiceData
- added WebService-Part, Permission-Part, Exception-Part
- added Unit-Tests for WebService-Part, Permission-Part, Exception-Part
- added Integrationtest
(todo: validation still has to be updated in core)
=> Add Web service start

integrations/standalone/tests/integration/activites/interface/webservice.spec.ts, integrations/standalone/tests/integration/events/start/ws.spec.ts, integrations/standalone/tests/integration/parts/index.ts, integrations/standalone/tests/integration/parts/ws-request.ts, integrations/standalone/tests/pageobjects/Select.ts, packages/editor/src/components/editors/activity/interface.tsx, packages/editor/src/components/editors/event/webservice.tsx, packages/editor/src/components/parts/common/mapping-tree/MappingPart.tsx, packages/editor/src/components/parts/index.ts, packages/editor/src/components/parts/ws-request/WsClientSelect.test.tsx, packages/editor/src/components/parts/ws-request/WsClientSelect.tsx, packages/editor/src/components/parts/ws-request/WsMapping.test.tsx, packages/editor/src/components/parts/ws-request/WsMapping.tsx, packages/editor/src/components/parts/ws-request/WsOperationSelect.test.tsx, packages/editor/src/components/parts/ws-request/WsOperationSelect.tsx, packages/editor/src/components/parts/ws-request/WsPortSelect.test.tsx, packages/editor/src/components/parts/ws-request/WsPortSelect.tsx, packages/editor/src/components/parts/ws-request/WsProperties.test.tsx, packages/editor/src/components/parts/ws-request/WsProperties.tsx, packages/editor/src/components/parts/ws-request/WsRequestPart.test.tsx, packages/editor/src/components/parts/ws-request/WsRequestPart.tsx, packages/editor/src/components/parts/ws-request/properties.test.ts, packages/editor/src/components/parts/ws-request/properties.ts, packages/editor/src/components/parts/ws-request/useWsRequestData.ts, packages/editor/src/test-utils/test-utils.tsx, packages/protocol/src/data/inscription-data.ts, packages/protocol/src/data/part-data.ts, packages/protocol/src/data/workflow-data.ts, packages/protocol/src/defaults/common-defaults.ts, packages/protocol/src/inscription-protocol.ts
=> XIVY-11712 Add Ws Call request

integrations/standalone/tests/integration/activites/interface/webservice.spec.ts, integrations/standalone/tests/integration/parts/index.ts, integrations/standalone/tests/integration/parts/ws-response.ts, packages/editor/src/components/editors/activity/interface.tsx, packages/editor/src/components/parts/index.ts, packages/editor/src/components/parts/ws-response/WsRequestPart.test.tsx, packages/editor/src/components/parts/ws-response/WsRequestPart.tsx, packages/editor/src/components/parts/ws-response/useWsRequestData.ts, packages/protocol/src/data/part-data.ts, packages/protocol/src/data/workflow-data.ts
=> XIVY-11712 Add Ws call response

packages/protocol/src/data/inscription.ts
depends upon https://github.com/axonivy/inscription-client/pull/307
=> XIVY-11705 consume program.widgets

packages/protocol/src/data/inscription.ts
depends upon https://github.com/axonivy/core/pull/3886/
=> apply rest.payload fix

integrations/standalone/tests/integration/parts/rest-request.ts, integrations/standalone/tests/integration/project/config/rest-clients.yaml, integrations/standalone/tests/integration/project/config/variables.yaml, packages/editor/src/components/parts/rest-request/RestRequestPart.tsx, packages/editor/src/components/parts/rest-request/rest-target/RestParameters.tsx, packages/editor/src/components/parts/rest-request/rest-target/RestTargetUrl.css, packages/editor/src/components/parts/rest-request/rest-target/RestTargetUrl.test.tsx, packages/editor/src/components/parts/rest-request/rest-target/RestTargetUrl.tsx, packages/editor/src/components/parts/rest-request/rest-target/parameters.test.ts, packages/editor/src/components/parts/rest-request/rest-target/parameters.ts, packages/editor/src/components/parts/rest-request/rest-target/usePathParams.test.ts, packages/editor/src/components/parts/rest-request/rest-target/usePathParams.ts, packages/editor/src/test-utils/test-utils.tsx, packages/protocol/src/inscription-protocol.ts
based on https://github.com/axonivy/core/pull/3890
=> Rest request url

packages/editor/src/components/browser/Browser.css, packages/editor/src/components/browser/CmsBrowser.test.tsx, packages/editor/src/components/browser/CmsBrowser.tsx, packages/editor/src/components/parts/common/mapping-tree/MappingPart.test.tsx, packages/editor/src/components/widgets/code-editor/MacroArea.tsx, packages/editor/src/components/widgets/code-editor/useCodeEditor.ts, packages/editor/src/components/widgets/table/cell/ExpandableCell.tsx, packages/editor/src/components/widgets/table/row/SelectRow.tsx, packages/editor/src/test-utils/test-utils.tsx, packages/protocol/src/data/inscription.ts, packages/protocol/src/inscription-protocol.ts
First Version of CMS-Browser:
I would appreciate feedback for my current code.
ToDo:
- RequiredProjects: I don't quite understand what I need this for yet?
- Search: I don't know or still need to figure out how the search works in general and how I can additionally search for the content.
- Insert: If the current value is "", the result is still <%=%>. I have now called attention to this situation using the Helper Text, because I don't quite understand how to modify the accept().
- UT: I have written two simple UT, maybe I can further improve them
- IT: I have not written any IT's yet.
=> XIVY-11798 Add CMS-Browser

packages/editor/src/components/browser/Browser.tsx, packages/editor/src/components/browser/CmsBrowser.tsx, packages/editor/src/components/browser/useOnFocus.ts, packages/editor/src/components/parts/common/parameter/ParameterTable.tsx, packages/editor/src/components/parts/end-page/EndPagePart.tsx, packages/editor/src/components/widgets/code-editor/MacroArea.tsx, packages/editor/src/components/widgets/code-editor/MacroInput.tsx, packages/editor/src/components/widgets/code-editor/ScriptInput.tsx, packages/editor/src/components/widgets/code-editor/useCodeEditor.ts, packages/editor/src/components/widgets/input/Input.css, packages/editor/src/components/widgets/input/InputWithBrowser.tsx, packages/editor/src/components/widgets/table/cell/EditableCell.css, packages/editor/src/components/widgets/table/cell/EditableCell.tsx
Added string/file validation to cms browser (cms.co or cms.cr)
Added extended content-search to cms browser
Added EndPart - Input with Browser
Added EditableCell with Browser
=> XIVY-11798 Add improvements for all-browsertypes

packages/editor/src/components/editors/InscriptionEditor.tsx, packages/editor/src/components/editors/part/Part.test.tsx, packages/editor/src/components/editors/part/Part.tsx, packages/editor/src/components/widgets/accordion/Accordion.css
I think I can remove the summary from the accordion or should I leave it for now?
=> XIVY-12552 Add one accordion open functionality

packages/editor/src/components/browser/CmsBrowser.tsx, packages/protocol/src/data/inscription.ts, packages/protocol/src/defaults/workflow-defaults.ts
After clicking the Add button, no window opens. Currently I do not see what is wrong. when I look at the code in the core I do not think I need to add anything else.
=> Cms browser add string button

integrations/standalone/src/index.css, packages/editor/src/App.css, packages/editor/src/components/browser/Browser.css, packages/editor/src/components/browser/Browser.tsx, packages/editor/src/components/editors/InscriptionEditor.css
Fix that the integrated inscription view
- Always shows a scrollbar
- Opens the browser full screen
=> XIVY-12602 Fix scrolling

packages/editor/src/components/widgets/accordion/Accordion.css, packages/editor/src/components/widgets/accordion/Accordion.tsx
=> XIVY-12552 Make accordion arrow clickable

packages/editor/src/components/parts/program/configuration/Configuration.css, packages/editor/src/components/parts/program/configuration/ConfigurationPart.tsx
I have corrected your suggestions. I hope that's all right 👍:
=> XIVY-12538 Fixed Label whitespace & Input width

packages/protocol/src/defaults/workflow-defaults.ts
Fixed notification type conflict
=> XIVY-4422 Fixed notification type

config/base.eslintrc.json
Is not a problem any more that eslint has troubles with the imports of esm bundles
=> Enable eslint rule import/no-unresolved again

build/Jenkinsfile, build/integration/Jenkinsfile, build/screenshots/Jenkinsfile, integrations/standalone/tsconfig.json
Improve junt reporting pattern
=> Fix eslint reporting on jenkins

packages/editor/src/App.css, packages/editor/src/components/widgets/message/Message.css, packages/editor/src/components/widgets/output/CardText.css, packages/editor/src/components/widgets/table/header/TableHeader.css, packages/editor/src/components/widgets/table/row/MessageRow.css
=> XIVY-12800 Added border around error/warning-row

integrations/standalone/tests/mock/code-editor-input.spec.ts, packages/editor/src/App.css, packages/editor/src/components/browser/Browser.css, packages/editor/src/components/editors/InscriptionEditor.css, packages/editor/src/components/widgets/select/Select.tsx, packages/editor/src/components/widgets/tab/Tab.css, packages/editor/src/components/widgets/table/row/MessageRow.css
=> XIVY-12800 Fixed dropdown and font tablist

packages/editor/src/App.css, packages/editor/src/components/browser/Browser.css, packages/editor/src/components/browser/Browser.tsx, packages/editor/src/components/browser/DataTypeBrowser.tsx, packages/editor/src/components/widgets/checkbox/Checkbox.css, packages/editor/src/components/widgets/combobox/Combobox.css, packages/editor/src/components/widgets/fieldset/Fieldset.css, packages/editor/src/components/widgets/radio/Radio.css, packages/editor/src/components/widgets/select/Select.css, packages/editor/src/components/widgets/table/row/SelectRow.css, packages/editor/src/query/QueryProvider.tsx
- Adjust the shades of blue
- Enhance the visibility of radio buttons and checkboxes in dark mode.
- Implemented feedback for the datatype browser: relocate the "Use Type as List" checkbox to the bottom and introduce an information cell indicating that entering a search term is required to display results.
=> XIVY-12800 Adjust color, radio/checkbox/datatypeb.

packages/editor/src/App.tsx, packages/editor/src/components/browser/AttributeBrowser.tsx, packages/editor/src/components/parts/common/exception-handler/ExceptionSelect.tsx, packages/editor/src/components/parts/common/responsible/useRoles.ts, packages/editor/src/components/parts/condition/ConditionPart.tsx, packages/editor/src/components/parts/output/OutputPart.tsx, packages/editor/src/components/parts/query/database/TableFields.tsx, packages/editor/src/components/parts/query/database/TableReadFields.tsx, packages/editor/src/components/parts/query/database/TableSelect.tsx, packages/editor/src/components/parts/query/database/TableSort.tsx, packages/editor/src/components/parts/rest/RestResponsePart.tsx, packages/editor/src/components/parts/result/ResultPart.tsx, packages/editor/src/components/parts/start/StartPart.tsx, packages/editor/src/components/parts/web-service/WebServicePart.tsx, packages/editor/src/components/parts/ws-response/WsResponsePart.tsx, packages/editor/src/components/widgets/code-editor/CodeEditor.tsx, packages/editor/src/context/useAction.ts, packages/editor/src/context/useEditorContext.ts
Else it is in the tanstack query cache key, so if another element requests the same data, it can not be reused from the cache
=> XIVY-12560 Only use pid where it is needed

packages/editor/src/components/browser/CmsBrowser.tsx
=> XIVY-11798 Change refresh-icon and type-info

integrations/standalone/tests/integration/project/pom.xml, integrations/standalone/tests/screenshots/project/pom.xml
Raising project-build-plugin version to 11.2.0 / 11.2.1-SNAPSHOT
=> Raising project-build-plugin version to 11.2.0 / 11.2.1-SNAPSHOT

integrations/standalone/package.json, integrations/standalone/tests/screenshots/pom.xml, integrations/standalone/tests/screenshots/project/pom.xml, lerna.json, packages/core/package.json, packages/editor/package.json, packages/icons/package.json, packages/protocol/package.json
Raise version to 11.3.0-SNAPSHOT
=> Raise version to 11.3.0-SNAPSHOT

integrations/standalone/tests/integration/project/pom.xml, integrations/standalone/tests/screenshots/project/pom.xml
Raising project-build-plugin version to 11.2.0 / 11.3.0-SNAPSHOT
=> Raising project-build-plugin version to 11.2.0 / 11.3.0-SNAPSHOT

packages/editor/src/components/widgets/select/Select.tsx
Same as on master: https://github.com/axonivy/inscription-client/pull/413
=> Fix select menu pos > R11.2

.ivy/raise-version.sh, integrations/standalone/tests/integration/project/pom.xml
- Because some pom.xml files where moved
- Before this error was just swallowed, now it is visible with 'set -e'
=> Fix raise version script

packages/editor/src/components/editors/InscriptionEditor.css, packages/editor/src/components/widgets/accordion/Accordion.css, packages/editor/src/components/widgets/button/Button.css, packages/editor/src/components/widgets/checkbox/Checkbox.css, packages/editor/src/components/widgets/popover/Popover.css, packages/editor/src/components/widgets/tab/Tab.css, packages/editor/src/components/widgets/tag/Tags.css
Same as on master: https://github.com/axonivy/inscription-client/pull/417
=> Remove global button unset > R11.2

packages/editor/src/components/widgets/popover/Popover.css, packages/editor/src/components/widgets/table/cell/CodeEditorCell.tsx, packages/editor/src/components/widgets/tag/Tags.tsx
Same as on master: https://github.com/axonivy/inscription-client/pull/419
=> Fix popover collisionBoundary aware > R11.2

integrations/standalone/tsconfig.json, packages/core/tsconfig.json, packages/editor/tsconfig.json, packages/icons/tsconfig.json, packages/protocol/tsconfig.json
See: https://github.com/eclipse-theia/theia/pull/12981
=> Remove baseUrl form tsconfig's

config/tsconfig.base.json
According to: https://www.totaltypescript.com/tsconfig-cheat-sheet
=> Use target ES2022

packages/editor/src/components/parts/name/GeneralPart.tsx, packages/editor/src/components/widgets/input/Input.tsx, packages/editor/src/components/widgets/input/Textarea.tsx
master: https://github.com/axonivy/inscription-client/pull/424
=> XIVY-12896 Fix cursor position loose on input/textarea > R11.2

packages/editor/src/components/widgets/checkbox/Checkbox.css, packages/editor/src/components/widgets/radio/Radio.css
master: https://github.com/axonivy/inscription-client/pull/426
=> XIVY-12896 Disable shrink on radio / checkboxes > R11.2

packages/editor/src/components/editors/activity/workflow.tsx, packages/editor/src/components/parts/call/dialog/DialogCallPart.tsx, packages/protocol/src/data/inscription.ts, packages/protocol/src/inscription-protocol.ts
core: https://github.com/axonivy/core/pull/4421
=> XIVY-12896 Support hide offline dialog starts

packages/editor/src/components/widgets/select/Select.tsx
master https://github.com/axonivy/inscription-client/pull/430
=> Fix customfield select position

integrations/standalone/tests/pageobjects/Table.ts
master: https://github.com/axonivy/inscription-client/pull/440
=> Stabilize table clean > R11.2

packages/editor/src/components/parts/output/OutputScriptPart.tsx, packages/editor/src/components/widgets/code-editor/CodeEditor.css, packages/editor/src/components/widgets/code-editor/ScriptArea.css, packages/editor/src/components/widgets/input/Textarea.tsx, packages/editor/src/components/widgets/popover/Popover.css
- Fix monaco selection in popup
- Init height of script code block equals code
- Browser button in script-area should always be over scrollbar
=> XIVY-13052 Small monaco fixes

integrations/standalone/tests/mock/browser.spec.ts, packages/editor/src/components/browser/Browser.tsx, packages/editor/src/components/browser/TypeBrowser.tsx, packages/editor/src/components/widgets/code-editor/MacroArea.tsx, packages/editor/src/components/widgets/code-editor/MacroInput.tsx, packages/editor/src/components/widgets/code-editor/ScriptArea.tsx, packages/editor/src/components/widgets/code-editor/ScriptInput.tsx, packages/editor/src/components/widgets/code-editor/useCodeEditor.ts, packages/editor/src/components/widgets/combobox/Combobox.tsx, packages/editor/src/components/widgets/table/cell/CodeEditorCell.tsx
I hope my approach is OK. there is already the functionality that the selected text is replaced but I have not seen anywhere that the content of the selected text is already saved somewhere.
=> XIVY-13055 Add selected Text to search in Typebrow

packages/editor/src/components/browser/Browser.tsx, packages/editor/src/components/browser/FunctionBrowser.tsx, packages/editor/src/components/widgets/code-editor/useCodeEditor.ts, packages/protocol/src/data/inscription.ts, packages/protocol/src/inscription-protocol.ts
=> XIVY-12549 Add simple functionbrowser

packages/editor/src/components/browser/AttributeBrowser.test.tsx, packages/editor/src/components/browser/AttributeBrowser.tsx, packages/editor/src/components/browser/Browser.tsx, packages/editor/src/components/browser/CatPathChooser.tsx, packages/editor/src/components/browser/CmsBrowser.test.tsx, packages/editor/src/components/browser/CmsBrowser.tsx, packages/editor/src/components/browser/FunctionBrowser.tsx, packages/editor/src/components/browser/SqlOperationBrowser.tsx, packages/editor/src/components/browser/TableColBrowser.tsx, packages/editor/src/components/browser/TypeBrowser.tsx, packages/editor/src/components/browser/typeBrowser-utils.test.ts, packages/editor/src/components/browser/typeBrowser-utils.ts, packages/editor/src/components/browser/useBrowser.ts, packages/editor/src/components/widgets/code-editor/useCodeEditor.ts, packages/editor/src/components/widgets/combobox/Combobox.tsx, packages/editor/src/components/widgets/input/InputWithBrowser.tsx, packages/editor/src/test-utils/test-utils.tsx
Cherry-Pick adjusted Typebrowser to 11.2.1
=> XIVY-12992 Fix defaulttypes for typebrowser

packages/editor/src/components/widgets/table/cell/EditableCell.tsx
=> XIVY-12992 Fix ParameterTable with browser

packages/editor/src/components/browser/MaximizedCodeEditorBrowser.tsx, packages/editor/src/components/browser/maximizedCodeEditor/MaximizedCodeEditor.tsx, packages/editor/src/components/widgets/code-editor/ScriptArea.tsx
I managed to fix the slide-out animation. After experimenting a bit with this solution, the error has not recurred. However, since I'm not sure why the error occurred in the first place, I can't say with 100% certainty that it won't happen again. I also omitted the entire focusWithin, similar to the ScriptInputs.
=> XIVY-12797 Fix slide out animation

packages/editor/package.json, packages/editor/src/components/browser/function/FunctionBrowser.tsx, packages/editor/src/components/widgets/table/footer/TableFooter.css, packages/editor/src/components/widgets/table/footer/TableFooter.tsx, packages/editor/src/components/widgets/table/table/Table.tsx, yarn.lock
Improvement of the function browser search:
- The virtualizer is utilized.
- Only a maximum of 100 entries are displayed at a time. Additional entries (in increments of 100) can be loaded at the bottom.
- The data is loaded alphabetically, and the root is always expanded.
=> XIVY-13156 Imrpove Improvements for function browser search

integrations/standalone/src/mock/data-mock.ts, integrations/standalone/src/mock/inscription-client-mock.ts, integrations/standalone/src/mock/meta-mock.ts, integrations/standalone/tests/integration/events/start/start.spec.ts, integrations/standalone/tests/integration/parts/task.ts, integrations/standalone/tests/integration/project/cms/cms_en.yaml, packages/editor/src/components/parts/task/notification/NotificationPart.test.tsx, packages/editor/src/components/parts/task/notification/NotificationPart.tsx, packages/editor/src/components/parts/task/notification/TemplateSelect.tsx, packages/editor/src/components/parts/task/notification/useTemplates.ts, packages/editor/src/components/parts/task/options/TaskOptionsPart.test.tsx, packages/editor/src/components/parts/task/options/TaskOptionsPart.tsx, packages/editor/src/components/parts/task/task/Task.tsx, packages/protocol/src/data/inscription-data.ts, packages/protocol/src/inscription-protocol.ts
Add TemplateSelect
Add NotificationPart with TemplateSelect
Move Suppress Notification Checkbox from TaskOptionsPart to NotificationPart Add NotificationPart to TaskPart
Rename TaskListPart to TaskOptionsPart
Add mock for /meta/workflow/notificationTemplates
Add mock for WfNotification.template
=> XIVY-12796 Add task notification template

packages/editor/src/components/parts/task/notification/NotificationPart.tsx, packages/editor/src/components/parts/task/notification/TemplateSelect.tsx, packages/editor/src/components/parts/task/notification/useTemplates.ts
Use defaultTask values to decide if the notification section is open by default or not.
If template is missing in available template add current template to the list of values instead of showing the Default value.
=> XIVY-12796 Show missing template value. Use defaultTask

integrations/standalone/package.json, integrations/standalone/tests/integration/project/pom.xml, integrations/standalone/tests/screenshots/pom.xml, integrations/standalone/tests/screenshots/project/pom.xml, lerna.json, packages/core/package.json, packages/editor/package.json, packages/icons/package.json, packages/protocol/package.json
Raise version to 11.2.2-SNAPSHOT
=> Raise version to 11.2.2-SNAPSHOT

packages/editor/src/components/parts/common/customfield/CustomFieldTable.tsx, packages/editor/src/components/parts/common/customfield/StartCustomFieldTable.tsx, packages/editor/src/components/parts/common/parameter/ParameterTable.tsx, packages/editor/src/components/parts/common/path/validation/ValidationRow.tsx, packages/editor/src/components/parts/common/table/useResizableEditableTable.ts, packages/editor/src/components/parts/name/document/DocumentTable.tsx, packages/editor/src/components/widgets/table/row/MessageRow.test.tsx, packages/editor/src/components/widgets/table/row/MessageRow.tsx, packages/editor/src/components/widgets/table/row/ReorderRow.tsx, packages/editor/src/components/widgets/table/row/SelectRow.tsx
I created my own use-hook to reuse the table, as well as rowSelection and add/remove row functions. What do you think about that? Maybe the naming of the custom hook could be improved 😅 
Additionally, I have also improved the SelectableValidationRow as mentioned in the previous PR.
=> XIVY-13253 Add custom Table use-hook and improve SelectableValidationRow

build/Jenkinsfile, integrations/standalone/src/url-helper.ts
Even if the inscription client is served secure with https
=> Allow to connect to an unsecure websocket

integrations/standalone/src/mock/data-mock.ts, integrations/standalone/src/mock/inscription-client-mock.ts, integrations/standalone/src/mock/meta-mock.ts, integrations/standalone/tests/mock/browser.spec.ts, packages/editor/src/components/browser/Browser.tsx, packages/editor/src/components/browser/role/RoleBrowser.tsx, packages/editor/src/components/browser/useBrowser.ts, packages/editor/src/components/parts/common/responsible/ResponsibleSelect.tsx, packages/editor/src/components/parts/common/responsible/RoleSelect.css, packages/editor/src/components/parts/common/responsible/RoleSelect.tsx, packages/editor/src/components/parts/common/responsible/useRoles.ts
I have implemented the Role Selector Browser along with corresponding IT.
Additionally, I have also created IT for the Table Column Browser.
=> XIVY-13091: Add Role Selector Browser and IT to ColBrowser

packages/editor/src/components/widgets/tag/Tags.css, packages/editor/src/components/widgets/tag/Tags.test.tsx, packages/editor/src/components/widgets/tag/Tags.tsx, packages/editor/src/test-utils/test-utils.tsx, packages/protocol/src/inscription-protocol.ts
I have revised the tags according to Anais's design. Now I need to create metadata to populate the dropdown with the correct tags.
=> XIVY-11891: Create new Tags

build/Jenkinsfile, build/playwright/Dockerfile, integrations/standalone/package.json, integrations/standalone/src/mock/validation-mock.ts, integrations/standalone/tests/mock/validation.spec.ts, integrations/standalone/tests/pageobjects/Combobox.ts, yarn.lock
- Update playwright to v1.42.1
- Update vite to v5.2.8
=> XIVY-13510 Add mock tests for validaiton style

integrations/standalone/tests/integration/parts/request.ts, packages/editor/src/components/parts/cache/CachePart.tsx, packages/editor/src/components/parts/request/RequestPart.test.tsx, packages/editor/src/components/parts/request/RequestPart.tsx, packages/editor/src/components/parts/task/expiry/ExpiryPart.test.tsx, packages/editor/src/components/parts/task/expiry/ExpiryPart.tsx, packages/editor/src/components/widgets/checkbox/Checkbox.tsx
- Rename 'Start list' to 'Show on start list'
- Hide details if 'Show on start list' is unchecked
- Elements outside of collapsible should have inline padding
=> XIVY-13510 Improve elements outside of collapsible

integrations/standalone/package.json, packages/core/package.json, packages/editor/package.json, packages/editor/src/components/browser/BrowserBody.css, packages/editor/src/components/editors/InscriptionEditor.css, packages/editor/src/components/editors/part/Part.css, packages/editor/src/components/editors/part/Part.tsx, packages/editor/src/components/editors/part/useSticky.ts, packages/editor/src/test-utils/setupTests.tsx, yarn.lock
=> XIVY-13510 Sticky accordion

integrations/standalone/package.json, integrations/standalone/tests/integration/parts/configuration.ts, packages/core/package.json, packages/editor/package.json, packages/editor/src/components/parts/common/mapping-tree/MappingTree.tsx, packages/editor/src/components/parts/program/configuration/Configuration.css, packages/editor/src/components/parts/program/configuration/ConfigurationPart.tsx, packages/editor/src/components/widgets/table/cell/CodeEditorCell.css, yarn.lock
- Add collapsible to thridparty configuration section
- Mapping table default column size changes
- Fix placeholder styles for CodeEditorCell
=> XIVY-13510 Adapt UI

integrations/standalone/tests/screenshots/activities/interface.spec.ts, integrations/standalone/tests/screenshots/activities/workflow.spec.ts, integrations/standalone/tests/screenshots/events/start.spec.ts, integrations/standalone/tests/screenshots/other/common.spec.ts
After the name change, some screenshots no longer worked. Here is a first fix. After getting feedback from bruno, I will finalize the documentation.
=> Fix inscription screenshots

packages/editor/src/components/browser/BrowserBody.css, packages/editor/src/components/widgets/tab/Tab.css
- Browser background color
- Tab border only on keyboard focus
=> Fix browser styles

packages/editor/src/components/browser/BrowserBody.css, packages/editor/src/components/widgets/tab/Tab.css
- Browser background color
- Tab border only on keyboard focus
master: https://github.com/axonivy/inscription-client/pull/583
=> Fix browser styles > R11.3

packages/editor/src/components/widgets/output/CardText.css
https://github.com/axonivy/inscription-client/pull/596
=> Fix: Spacing between card-text-line with auto-word-wrap

packages/editor/src/components/parts/ws-request/WsOperationSelect.tsx, packages/protocol/src/data/inscription.ts
- it was removed form the ivy-core
=> XIVY-14832 remove Soap WebServiceTester button

packages/editor/src/components/editors/ProcessOutline.tsx, packages/protocol/src/inscription-protocol.ts
https://github.com/axonivy/core/pull/6641
=> XIVY-14827 Use InscriptionElementContext for outline meta

build/integration/Jenkinsfile, build/screenshots/Jenkinsfile, playwright/tests/screenshots/assembly.xml
Missed some stages which only where triggered on the master branch
=> Fix pipelines for master
