- .ivy/raise-build-plugin-version.sh
- .ivy/raise-version.sh
- Jenkinsfile
- build/Dockerfile
- build/engine/Jenkinsfile
- build/screenshots/Jenkinsfile
- build/use-mirror-npm.sh
- Use playwright jammy image (Ubuntu 22.04)
- Install maven via apt
- Use mirror npm for CI
- Add raise version scripts
> Improve build infrastructure

- integrations/standalone/tests/engine/tabs/output-tab.ts
- integrations/standalone/tests/engine/tabs/task-tab.ts
Hi @ivy-rew 
This PR enables the unstable/wrong assertions
[Client build](https://jenkins.ivyteam.io/job/inscription-view/job/all-engine-tests/)
[Engine Integration Build](https://jenkins.ivyteam.io/job/inscription-view-integration/job/all-engine-tests/)
[Screenshots](https://jenkins.ivyteam.io/job/inscription-view-screenshot/job/all-engine-tests/)
> Enable all engine integration tests

- packages/editor/src/components/parts/call/CallSelect.tsx
- packages/editor/src/components/parts/call/dialog/DialogCallPart.tsx
- packages/editor/src/components/parts/call/sub/SubCallPart.tsx
- packages/editor/src/components/parts/call/trigger/TriggerCallPart.tsx
- packages/editor/src/components/parts/name/NamePart.tsx
- packages/editor/src/components/parts/task/error/ErrorSelect.tsx
- packages/editor/src/components/parts/task/expiry/ExpiryPart.test.tsx
- packages/editor/src/components/parts/task/general/TaskPart.test.tsx
- packages/editor/src/components/parts/task/priority/PrioritySelect.css
- packages/editor/src/components/parts/task/priority/PrioritySelect.tsx
- packages/editor/src/components/parts/task/responsible/ResponsibleSelect.css
- packages/editor/src/components/parts/task/responsible/ResponsibleSelect.test.tsx
- packages/editor/src/components/parts/task/responsible/ResponsibleSelect.tsx
- packages/editor/src/components/widgets/combobox/Combobox.css
- packages/editor/src/components/widgets/combobox/Combobox.test.tsx
- packages/editor/src/components/widgets/combobox/Combobox.tsx
- packages/editor/src/components/widgets/fieldset/Fieldset.test.tsx
- packages/editor/src/components/widgets/fieldset/Fieldset.tsx
- packages/editor/src/components/widgets/input/Textarea.tsx
- packages/editor/src/components/widgets/select/Select.css
- packages/editor/src/components/widgets/select/Select.test.tsx
- packages/editor/src/components/widgets/select/Select.tsx
- packages/editor/src/components/widgets/table/cell/CodeEditorCell.tsx
- packages/editor/src/components/widgets/table/cell/EditableCell.tsx
- packages/editor/src/components/widgets/table/cell/SelectCell.css
- packages/editor/src/components/widgets/table/cell/SelectCell.tsx
- packages/editor/src/components/widgets/tag/Tags.tsx
- packages/editor/src/test-utils/select-utils.tsx
- packages/editor/src/utils/utils.ts
Widget (like combobox, select) should not longer provide a label itself. The user of a such widget should wrap them into a Fieldset component.
- Add fieldset hook to build label and input props to link them together
- Refactor fieldsets out of combobox and select widgets
> Refactor widgets

- packages/core/src/ivy-script-client.ts
- packages/editor/src/components/widgets/code-editor/CodeEditor.tsx
- packages/editor/src/monaco/ivy-macro-language.ts
- packages/editor/src/monaco/monaco-editor-util.ts
Add own Monaco language for ivy macros and provide highlighting of <% and %>
Also support that %> is auto inserted if <% is inserted
ivyScript and ivyMacro language is served by the same LSP
> XIVY-11675 Add own monaco language for ivy macros

- integrations/standalone/tests/utils/code-editor-util.ts
- packages/editor/src/components/browser/AttributeBrowser.tsx
- packages/editor/src/components/widgets/code-editor/MacroArea.tsx
- packages/editor/src/components/widgets/code-editor/MacroInput.tsx
- packages/editor/src/components/widgets/code-editor/ScriptInput.tsx
- packages/editor/src/components/widgets/code-editor/SingleLineCodeEditor.tsx
- packages/editor/src/components/widgets/code-editor/useCodeEditor.ts
- packages/editor/src/components/widgets/collapsible/CollapsiblePart.css
- packages/editor/src/components/widgets/table/cell/ScriptCell.tsx
- packages/editor/src/monaco/monaco-editor-util.ts
- Fix suggestion widget position
- Normal monaco's need to have this `fixedOverflowWidgets` option, but not the one in the mapping tree
- Fix Safari loose focus by clicking on the attribute browser
Looks like Safari is the next IE... 🤮
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus
- Fix react warning about missing key attribute in attribute browser
- Fix css gap in collapsable
> XIVY-11675 Small review fixes

- packages/editor/src/components/parts/condition/ConditionTable.tsx
- packages/editor/src/components/parts/task/expiry/ExpiryPart.tsx
- packages/editor/src/components/parts/task/options/TaskListPart.tsx
- packages/editor/src/components/parts/task/priority/PrioritySelect.tsx
- packages/editor/src/components/parts/task/responsible/ResponsibleSelect.tsx
- packages/protocol/src/data/workflow-data.ts
Currently, only the Inscription mask validator knows this.
But our ivyscript lsp currently does know nothing from the input except that evaluated variables.
If we would like to change this, we either need to make the ivyscript lsp more stateful or evaluate the real variable via the location. But if we do the second way, we also need to evaluate the value of a mapping tree, and this is something we definitely know in the frontend.
So I think it does no harm now if we send these types to the backend by now...
Or am I wrong?
> XIVY-11485 Script types

- integrations/standalone/src/url-helper.ts
Param pmv=workflow-demos%25241 from the Designer integration was not correclty decodet to 'workflow-demos$1'
> XIVY-10544 Fix pmv param decode

- integrations/standalone/src/mock/data-mock.ts
- integrations/standalone/tests/integration/parts/case.ts
- integrations/standalone/tests/integration/parts/task.ts
- integrations/standalone/tests/mock/code-editor-input.spec.ts
- integrations/standalone/tests/pageobjects/CodeEditor.ts
- integrations/standalone/tests/pageobjects/Composite.ts
- integrations/standalone/tests/pageobjects/ResponsibleSelect.ts
- packages/editor/src/App.css
- packages/editor/src/components/widgets/code-editor/MacroArea.tsx
- packages/editor/src/components/widgets/code-editor/MacroInput.tsx
- packages/editor/src/components/widgets/output/CardText.css
- packages/editor/src/components/widgets/output/CardText.test.tsx
- packages/editor/src/components/widgets/output/CardText.tsx
- packages/editor/src/utils/utils.test.ts
- packages/editor/src/utils/utils.ts
- Show output with card badges for macro expressions if macro editors are in read mode
- Init MacroArea monaco editor with the same height as the read mode was
- Specific CodeEditor page objects
> XIVY-12024 Add macro card text

- integrations/standalone/tests/integration/parts/call.ts
- integrations/standalone/tests/integration/parts/code.ts
- integrations/standalone/tests/integration/parts/output.ts
- integrations/standalone/tests/integration/parts/result.ts
- integrations/standalone/tests/integration/parts/start.ts
- integrations/standalone/tests/mock/code-editor-input.spec.ts
- integrations/standalone/tests/mock/reset.spec.ts
- integrations/standalone/tests/pageobjects/Accordion.ts
- integrations/standalone/tests/pageobjects/CodeEditor.ts
- integrations/standalone/tests/utils/code-editor-util.ts
- packages/editor/src/App.tsx
- packages/editor/src/components/widgets/accordion/Accordion.tsx
- packages/editor/src/components/widgets/code-editor/MacroArea.tsx
- packages/editor/src/components/widgets/code-editor/MacroInput.tsx
- packages/editor/src/components/widgets/code-editor/ScriptInput.tsx
- packages/editor/src/components/widgets/code-editor/index.ts
- packages/editor/src/components/widgets/code-editor/useCodeEditor.ts
- packages/editor/src/components/widgets/table/cell/ScriptCell.tsx
- packages/editor/src/test-utils/setupTests.tsx
- Fix broken reset functionality and add test for it
- Change MacroArea, MacroInput and ScriptInput fields -> save data not after every change only after focus loose
- Reduce pressure on server (especially in the test case)
- No nervous validation messages while write something (the validations are shown anyways in the monaco editor)
> Fix reset functionality

- packages/editor/src/components/parts/permissions/PermissionsPart.tsx
Process permissions don't have any validation (checkbox), so we don't need to have validations on the part.
> XIVY-11707 Remove process permission validation

- packages/editor/src/components/editors/activity/interface.tsx
- packages/editor/src/components/editors/event/intermediate.tsx
- packages/editor/src/components/editors/event/start.tsx
- packages/editor/src/components/parts/index.ts
- packages/editor/src/components/parts/program/JavaClassSelector.test.tsx
- packages/editor/src/components/parts/program/activity/ProgramInterfaceStartPart.test.tsx
- packages/editor/src/components/parts/program/editor/Editor.css
- packages/editor/src/components/parts/program/editor/EditorPart.test.tsx
- packages/editor/src/components/parts/program/editor/EditorPart.tsx
- packages/editor/src/components/parts/program/editor/useEditorData.ts
- packages/editor/src/components/parts/program/event/ProgramStartPart.test.tsx
- packages/editor/src/test-utils/test-utils.tsx
- packages/protocol/src/data/part-data.ts
- packages/protocol/src/inscription-protocol.ts
First simple version of the EditorPart.
I haven't really separated the component yet, nor have I created any unit or integration tests. I think since it is not 100% known how or what data I will get from the backend I should not invest too much time in testing and separating the current solution. what do you think?
I also tried to format the multiline-label-text using linebreaks similar to the current version but I'm not satisfied yet. The current texts are separated quite randomly at certain places with linebreaks, so the separation-expression for these texts could become extremely long and unattractive. maybe i could skip this part at the moment as well.
> XIVY-11705 Add EditorPart

- packages/editor/src/components/parts/common/eventcode/EventCodeSelect.tsx
- packages/editor/src/components/parts/rest/RestEntityTypeCombobox.tsx
- packages/editor/src/components/parts/signal/SignalCatchPart.tsx
- packages/editor/src/components/widgets/combobox/Combobox.css
- packages/editor/src/components/widgets/combobox/ComboboxWithBrowser.tsx
I have now created a combobox to which a browser can be added. I managed to implement this combobox in:
- Signal Boundary --> Signal Code
- Rest Client --> Request --> Body -->Entity type
- Rest Client --> Response --> Read body as type.
What is still missing in the Signal Boundary is the support of MacroInput. Currently there is an error message when an element is added to the combobox of the Signal Boundary via Attribute Browser. Should I also take a look at this in this PR or does the improvement of the signal input belong to another story?
> Add browser to rest signal

- packages/editor/src/components/browser/Browser.css
- packages/editor/src/components/browser/CmsBrowser.test.tsx
- packages/editor/src/components/browser/CmsBrowser.tsx
- packages/editor/src/components/browser/DataTypeBrowser.test.tsx
- packages/editor/src/components/browser/DataTypeBrowser.tsx
- packages/editor/src/components/widgets/collapsible/Collapsible.tsx
- packages/editor/src/components/widgets/input/InputWithBrowser.tsx
- packages/editor/src/test-utils/test-utils.tsx
- packages/protocol/src/data/inscription.ts
- packages/protocol/src/inscription-protocol.ts
First version of the datatype browser and unittests.
I commented out one useEffect in the Datatype-Browser (see reason in the comment itself). What do you think? Should this filter be handled in the backend instead?
Also I used margin in the Browser.css at one point because I couldn't (quickly) achieve it with display: flex and gap. I might try that again to improve it.
Additionally I added a little help, if someone has the checkbox "Use Type as List" set and then searches for lists, he gets a corresponding info that he has to uncheck it if he wants to see lists. Maybe unnecessary (I can also remove it) but I wanted to try it out :-).
ToDo (for another PR):
- IT for Mock
- Still missing the fixed metas for the Ivy datatypes
- Due to the lazy search it is not possible to find elements that …
> XIVY-12548 Add Datatype Browser

- packages/editor/src/components/browser/Browser.tsx
- packages/editor/src/components/widgets/code-editor/MacroArea.tsx
- packages/editor/src/components/widgets/code-editor/MacroInput.tsx
- packages/editor/src/components/widgets/code-editor/ScriptArea.tsx
- packages/editor/src/components/widgets/code-editor/ScriptInput.tsx
- packages/editor/src/components/widgets/code-editor/useCodeEditor.ts
- packages/editor/src/components/widgets/combobox/Combobox.test.tsx
- packages/editor/src/components/widgets/combobox/Combobox.tsx
I could adjust the 'accept' to include the browser type, and based on that, along with a flag to ensure that it only affects the ScriptArea, I was able to achieve the "import functionality." 
Unfortunately, all the tests of the components with a combobox are failing. As you can see, I haven't made any changes to the combobox or anything similar, so I have no idea why this is suddenly failing, especially when it didn't fail in the PR where I added the editor to the combobox. What should I do now? Should I revert the macro functionality of the combobox, or should I mock the whole thing (as you briefly mentioned before)? If the mock approach is appropriate, we should have a quick call again, as I didn't quite understand how that works.
> XIVY-12548 Add browsertype to accept

- packages/editor/src/components/browser/DataTypeBrowser.tsx
- packages/protocol/src/data/inscription.ts
I have set the limit to 100 and reduced the waiting time to 150ms. With the limit, the search is much faster now. The part 'loading more types...' is now practically invisible to me.
> XIVY-12548 Add limit to allType-search

- integrations/standalone/package.json
Because tsc --build does also not emit, because tsconfig says noEmit: true
> Use faster tsc --build instead of tsc --noEmit

- packages/editor/src/App.css
- packages/editor/src/components/browser/AttributeBrowser.test.tsx
- packages/editor/src/components/browser/AttributeBrowser.tsx
- packages/editor/src/components/browser/Browser.css
- packages/editor/src/components/browser/Browser.tsx
- packages/editor/src/components/browser/CmsBrowser.test.tsx
- packages/editor/src/components/browser/CmsBrowser.tsx
- packages/editor/src/components/browser/DataTypeBrowser.test.tsx
- packages/editor/src/components/browser/DataTypeBrowser.tsx
- packages/editor/src/components/parts/common/mapping-tree/MappingPart.test.tsx
- packages/editor/src/components/parts/rest/rest-request/rest-body/RestEntity.test.tsx
- packages/editor/src/components/widgets/accordion/Accordion.css
- packages/editor/src/components/widgets/checkbox/Checkbox.css
- packages/editor/src/components/widgets/code-editor/CodeEditor.css
- packages/editor/src/components/widgets/combobox/Combobox.css
- packages/editor/src/components/widgets/input/Input.css
- packages/editor/src/components/widgets/radio/Radio.css
- packages/editor/src/components/widgets/select/Select.css
- packages/editor/src/components/widgets/table/cell/ExpandableCell.css
- packages/editor/src/components/widgets/table/cell/ExpandableCell.tsx
- packages/editor/src/components/widgets/table/row/SelectRow.css
- packages/editor/src/components/widgets/table/row/SelectRow.tsx
- packages/editor/src/components/widgets/table/table/Table.css
- packages/editor/src/components/widgets/table/table/Table.tsx
Added doubleclick-insert to cms- & datatype-browser. Should I also add it to the attribute-browser?
Improved table- and helpertextheight for the browsers
Adjusted the paddingleft for Treetables/removed blue cirle
Made simpleName in Datatype-Browser bold
Color-Changes: 
- Better contrast (as Sprint-Review suggested)
- New Hover and Selectstate-color "blue" for Input/ScriptInput/Combobox/checkbox/radio/table
> Improve Design and Browserfunctionality

- packages/editor/src/App.tsx
- packages/editor/src/components/editors/InscriptionEditor.css
- packages/editor/src/components/parts/web-service/WebServicePart.tsx
- packages/editor/src/context/useEditorContext.ts
This affects the link on the webservice start which changes the inscription view to the webservice process.
As the old solution changes the url of the window, this solution works in the standalone inscription view, but not integrated into the process editor.
> XIVY-12684 Fix navigate to process in integration

- packages/editor/src/components/widgets/popover/Popover.css
- packages/editor/src/components/widgets/table/cell/CodeEditorCell.tsx
- packages/editor/src/components/widgets/tag/Tags.tsx
Add collisionBoundary to popover content to make it aware of the editor boundary
Before:
After:
> Fix popover collisionBoundary aware

- packages/editor/src/components/widgets/select/Select.tsx
sadly the offsetLeft seems not to be working in a table. So the getBoundingRect method was good, but we need remove the offset of the editor itself for the integration context.
> Fix customfield select position

- integrations/standalone/tests/pageobjects/Table.ts
I think, I finally found one of the lines that causes so many tests to flakines...
The problem here was that the clean method of the table iterates over every row and removes them, by checking the count of the rows.
But the await on the remove call only waits until the "button is clicked", but this doesn't mean that the code behind this button removed it from the table. So probably the next count on the rows happens with the previous row still visible.
With the check that the row count needs to be the current count - 1 it waits until this condition is true or fails if it is not.
> Stabilize e2e test

- integrations/standalone/tests/mock/browser.spec.ts
- packages/editor/src/components/browser/AttributeBrowser.tsx
- packages/editor/src/components/browser/CatPathChooser.tsx
- packages/editor/src/components/browser/CmsBrowser.tsx
- packages/editor/src/components/browser/FunctionBrowser.tsx
- packages/editor/src/components/browser/SqlOperationBrowser.tsx
- packages/editor/src/components/browser/TableColBrowser.tsx
- packages/editor/src/components/browser/TypeBrowser.tsx
- packages/editor/src/components/browser/useBrowser.ts
- packages/editor/src/components/widgets/input/IconInput.tsx
- packages/editor/src/components/widgets/tab/Tab.css
- packages/editor/src/components/widgets/tab/Tab.tsx
- packages/editor/src/components/widgets/table/cell/ExpandableCell.tsx
- packages/editor/src/components/widgets/table/table/Table.tsx
Adjusted Typebrowser:
- By default, only the most frequently used types (ivytypes and a few others) and data classes are displayed (sorted alphabetically, first by full qualified name and then by simple name).
- There is now a checkbox "Search over all types." When this is activated, the search is conducted over all types and the ivytypes/dataclasses are no longer displayed; otherwise, the search is limited to data classes and ivytypes.
- Open ToDos: Reguel still needs to create metadata for the type browser so that in addition to data classes and ivytypes, own custom-created classes/types are also visible. It will also be nessesary that two icons are designed, to indicate whether the type is a data class, an Ivy type, or a "normal type." Possibly, an icon for the own custom classes might …
> XIVY-12992 Improve Browsers & adjust Typebrowser

- packages/editor/src/components/browser/TypeBrowser.tsx
- packages/protocol/src/inscription-protocol.ts
I added the new 'ownType-Meta' so that now in the type browser, first all ownTypes are displayed, followed by DataClasses, and finally IvyTypes, including commonly used types. Additionally, I had to remove all data classes from ownTypes.data to avoid duplicates. The Icons are not perfect yet, still need to adress this to Anais.
> XIVY-12992 Add ownType Meta to Typebrowser

- packages/editor/src/components/browser/AttributeBrowser.test.tsx
- packages/editor/src/components/browser/AttributeBrowser.tsx
- packages/editor/src/components/browser/Browser.tsx
- packages/editor/src/components/browser/CatPathChooser.tsx
- packages/editor/src/components/browser/CmsBrowser.test.tsx
- packages/editor/src/components/browser/CmsBrowser.tsx
- packages/editor/src/components/browser/FunctionBrowser.tsx
- packages/editor/src/components/browser/SqlOperationBrowser.tsx
- packages/editor/src/components/browser/TableColBrowser.tsx
- packages/editor/src/components/browser/TypeBrowser.tsx
- packages/editor/src/components/browser/typeBrowser-utils.test.ts
- packages/editor/src/components/browser/typeBrowser-utils.ts
- packages/editor/src/components/browser/useBrowser.ts
- packages/editor/src/components/widgets/code-editor/useCodeEditor.ts
- packages/editor/src/components/widgets/combobox/Combobox.tsx
- packages/editor/src/components/widgets/input/InputWithBrowser.tsx
- packages/editor/src/test-utils/test-utils.tsx
Modified the default types in the Typebrowser as follows:
- Within code blocks, the default types are prioritized in the following order: 1. Own Types, 2. Data Classes, 3. Ivy Types (with the condition that, if applied, there should be no "import..." statement and also sorted alphabetically but all elements from java.lang/util should be displayed first).
- In all other sections, particularly in the mapping table, the default types are ordered as follows: 1. Data Classes, 2. Ivy Types.
> XIVY-12992 Fix defaulttypes for typebrowser

- packages/editor/src/components/widgets/table/cell/EditableCell.tsx
When adding a type from the browser using the ParameterTable for input parameters, only [Object object] appeared instead of the actual type. This occurred because I am now working not only with strings but also with the BrowserValue object. This adjustment ensures that the table functions smoothly again.
> XIVY-12992 Fix ParameterTable with browser

- packages/editor/src/components/widgets/table/cell/EditableCell.tsx
The problem was that the onBlur function was not being triggerd again after the accept of the browser, causing the table's meta not to be updated. Consequently, upon refreshing the component, the old value was displayed again. It worked perfectly if the type was entered directly into the input field, but it didn't work when the type was supposed to be defined using the typebrowser. Now, it should work as intended.
> XIVY-12992 Fix EditableCell with Browser

- packages/editor/src/components/browser/MaximizedCodeEditorBrowser.tsx
- packages/editor/src/components/browser/maximizedCodeEditor/MaximizedCodeEditor.tsx
- packages/editor/src/components/widgets/code-editor/ResizableCodeEditor.tsx
- packages/editor/src/components/widgets/code-editor/ScriptArea.tsx
- packages/editor/src/components/widgets/code-editor/useCodeEditor.ts
I have now implemented two features to the maximized code editor:
The maximized code editor can now be opened using the "F2" key.
The cursor position or selection from the minimized code editor is also transferred to the maximized code editor. Unfortunately, what doesn't work as well now is directly closing the browser again with the "Esc" key. To make this work, you have to first click outside the Monaco editor to lose focus and then it works.
What I have not implemented (yet) is transferring the cursor position and selection from the maximized code editor to the minimized code editor. However, I'm not sure if this is really necessary, as I don't expect someone to want to edit in the minimized editor immediately after working in the maximized code editor, especially right after clicking …
> XIVY-12797 Add open with f2 and adopt cursorPosition/selection feature

- integrations/standalone/tests/pageobjects/Table.ts
Currently, some IT are failing. As I have observed, the remove functionality does not work idealy with WebKit and Firefox. If there is only one row present and it is removed via a click on the remove button, the cleanup functionality is not always triggered. Therefore, I now additionally click the header to ensure that the empty rows are removed.
> Fix IT for General/Start/Result

- packages/editor/src/components/parts/common/info/Information.tsx
- packages/protocol/src/data/inscription.ts
I have now integrated the new core action into the frontend. For this action, I used the CMS browser icon.
> XIVY-12550 Add Cms-Action to category path chooser

- .imgbotconfig
This could be a way of disabling imgbot just for svg images. Generally the bot is enabled for all repositories on the axonivy organization at the moment ...
> Imgbot ignores svg images

- packages/editor/src/components/browser/role/RoleBrowser.tsx
I forgot to add this line of code, which resulted in the inscription crashing when something was first selected and then searched for something else in the search field. Now it works (this is already built into the other browsers).
> XIVY-13091: Fix search/insert bug for role browser

- integrations/standalone/tests/integration/parts/case.ts
- integrations/standalone/tests/integration/parts/request.ts
- integrations/standalone/tests/integration/parts/task.ts
- packages/editor/src/components/parts/common/customfield/CustomFieldTable.test.tsx
- packages/editor/src/components/parts/common/customfield/CustomFieldTable.tsx
- packages/editor/src/components/parts/common/customfield/StartCustomFieldTable.test.tsx
- packages/editor/src/components/parts/common/customfield/StartCustomFieldTable.tsx
- packages/editor/src/components/parts/common/info/Information.tsx
- packages/editor/src/components/parts/common/table/useResizableEditableTable.ts
- packages/editor/src/components/widgets/table/row/SelectRow.css
- packages/protocol/src/data/inscription.ts
- packages/protocol/src/inscription-protocol.ts
I added Combocells to the Custom Fields Table, inwhich known Custom Fields can be selected. If a known Custom Field is already in the Table it is no longer displayed in the dropdown. Also after selecting a Custom Field via the dropdown the type is also automatically adjusted.
There are UT I had to skip, because the test didn't work anymore with the combobox. Will fix it in a later PR.
> XIVY-11890: Add known Custom Fields to Table

- packages/editor/src/components/parts/common/parameter/ParameterTable.test.tsx
- packages/editor/src/components/parts/common/parameter/ParameterTable.tsx
To prevent errors when adding a new row to the parameter table, a default value is now added to the name. 
I've named it "change_this_name" to signal that the name needs to be changed. If the name isn't changed and the component is reloaded or the selection is lost, the new row will be removed from the table. I haven't named it "parameter" because I can imagine that this name might often be forgotten to be updated. 
What do you think?
> XIVY-13253: Prevents display of error on new line in parameter table

- integrations/standalone/tests/mock/browser/typeBrowser.spec.ts
- packages/editor/src/components/browser/type/TypeBrowser.tsx
- packages/editor/src/components/browser/type/cursor-value.test.ts
- packages/editor/src/components/browser/type/cursor-value.ts
- packages/editor/src/components/parts/common/info/Information.tsx
I have fixed a typo within the addCMS-Action for the Category-Field and also improved the import behavior of the type browser for the code block. It now behaves as follows:
Type browser opened within the code block:
**Import IvyType:** No "import ...", only the simple name of the IvyType is added.
**Import nonIvyType:** First line: import fullQualifiedName of Type, then only the simple name of the Type is added.
**Import IvyType as List:** No "import ...", only List<simple name of the IvyType> is added.
**Import nonIvyType as List:** First "import fullQualifiedName of Type", then List<simple name of the Types> is added.
Type browser not opened within a code block (the "import ..." line is always completely omitted):
**Import IvyType:** Only the simple name of the IvyType is added. …
> Fix import of typebrowser and typo inside addCms action

- integrations/standalone/tests/integration/activites/interface/rule.spec.ts
- integrations/standalone/tests/integration/parts/program-interface-start.ts
- packages/editor/src/components/editors/InscriptionEditor.tsx
- packages/editor/src/components/editors/third-party/all-third-party-editors.tsx
- packages/editor/src/components/editors/third-party/interface.tsx
- packages/editor/src/components/editors/third-party/intermediate.tsx
- packages/editor/src/components/editors/third-party/start.tsx
- packages/editor/src/components/parts/program/activity/ProgramInterfaceStartPart.tsx
- packages/editor/src/components/parts/program/event/ProgramStartPart.tsx
- packages/editor/src/components/parts/program/intermediate/EventPart.tsx
I have now added the three third-party editors (Rule, Intermediate-ThridPartyWait, Start-ThirdPartyStart). I have removed the Java class selector from both the Start and Event tabs for thirdparty-editors.
@ivy-lli  I have created a new folder "third-party" where I have placed all the thirdparty-editors. There are actually only three editors, which I could also simply incorporate into the "other-editors" TSX file. What do you think?
> XIVY-11709: First version of thirdparty-editors

- packages/editor/src/components/widgets/code-editor/CodeEditor.css
With this small fix, I can prevent the header text from overlapping other elements. Unfortunately, I don't really have the energy today to  figure out, how to send a shorter type for the header in the core. If you still wish to have the whole thing fixed in the core, I would create a follow-up story and address it after my vacation.
> XIVY-13506: Fix overflow of header inside autocompletion-details

- packages/editor/src/components/parts/trigger/TriggerPart.tsx
I have now customized the whole thing so that if no task has been selected yet, the same message appears as in the task tab. what do you think?
> XIVY-13987: Fix error if trigger-checkbox is selected with no task

- integrations/standalone/tests/integration/activites/interface/email.spec.ts
- integrations/standalone/tests/integration/activites/interface/restclient.spec.ts
- integrations/standalone/tests/integration/activites/interface/webservice.spec.ts
- integrations/standalone/tests/integration/parts/index.ts
- integrations/standalone/tests/integration/parts/mail-error.ts
- integrations/standalone/tests/integration/parts/mail-header.ts
- integrations/standalone/tests/integration/parts/output.ts
- integrations/standalone/tests/integration/parts/rest-output.ts
- integrations/standalone/tests/integration/parts/ws-output.ts
- integrations/standalone/tests/screenshots/activities/interface.spec.ts
- packages/editor/src/components/editors/activity/interface.tsx
- packages/editor/src/components/editors/gateway/all-gateway-editors.tsx
- packages/editor/src/components/parts/index.ts
- packages/editor/src/components/parts/mail/MailErrorPart.test.tsx
- packages/editor/src/components/parts/mail/MailErrorPart.tsx
- packages/editor/src/components/parts/mail/MailHeaderPart.test.tsx
- packages/editor/src/components/parts/mail/MailHeaderPart.tsx
- packages/editor/src/components/parts/mail/useMailData.ts
- packages/editor/src/components/parts/output/OutputPart.tsx
- packages/editor/src/components/parts/rest/RestOutputPart.tsx
I discussed the following points again with bruno and have now adjusted them:
- Output Data changed back to Output, as it is better to have only one word
- In the mail: Error section moved to its own (new) Error tab (analogous to the other elements, e.g. Rest...)
- Task-Switch-Gateway: Output-Tab was moved to the end like the other tabs
> XIVY-13806: Add improvement from feedback

- packages/editor/src/components/widgets/code-editor/ScriptArea.tsx
- packages/editor/src/monaco/monaco-editor-util.ts
I have improved the code block as follows (in minimized view):
- Autoscroll to the first line where there is no import
- If codeblock is empty the height is set to 90 and otherwise to 250
- When scrolling there is no shadow on top anymore (bruno didn't like it)
> XIVY-14079: For Codeblock - Adjust initHeight, scrollPosition & scrollShadow

- packages/editor/src/components/parts/query/database/Condition.tsx
- packages/editor/src/components/widgets/code-editor/MacroArea.tsx
- packages/editor/src/components/widgets/code-editor/ResizableCodeEditor.tsx
- packages/editor/src/components/widgets/code-editor/index.ts
- packages/editor/src/components/widgets/table/cell/CodeEditorCell.css
- packages/editor/src/components/widgets/table/cell/CodeEditorCell.tsx
- packages/editor/src/test-utils/setupTests.tsx
I have added an additional expand button to all CodeEditorCells within the monaco editor as well as an expand icon to the condition tab of the database element in the header.
The monaco can now be opened in fullscreen for both.
> Max code editor in script cell

- packages/editor/src/components/browser/MaximizedCodeEditorBrowser.tsx
- packages/editor/src/components/browser/maximizedCodeEditor/MaximizedCodeEditor.tsx
- packages/editor/src/components/widgets/code-editor/MacroArea.tsx
- packages/editor/src/components/widgets/table/cell/CodeEditorCell.tsx
In order for the maximized code editor (which I added to the expression cells and the condition in the db element), to display the correct validations in monaco, I had to forward the macro and type attributes.
> XIVY-14079: Fix validation for maximized code-editor

- packages/editor/src/components/parts/query/database/TableFields.tsx
If you select Any in the Database element and reload the Inscription and switch to another query (where the TableFields component is used), an NPE appears because config.query.sql.fields are undefined but are used within the TableFields component. 
With this fix NPE does not appear anymore, but I am not sure if this is the best way. What do you think?
https://1ivy.atlassian.net/browse/XIVY-14204
> XIVY-14204 fix: NPE for Database TableFields

- packages/editor/src/components/parts/query/database/Condition.tsx
- packages/editor/src/components/parts/query/database/TableReadFields.tsx
- packages/editor/src/components/parts/query/database/TableSort.tsx
- As with TableFields, an NPE occurred when switching from ANY to READ because orderBy was undefined.
- In addition, the defaultOpen was corrected accordingly.
- I wasn't quite sure if there was a shorter way of writing but I don't think so for these situations.
> XIVY-14204 Fix: NPE for Database-READ TableSort

- packages/editor/src/components/widgets/output/CardText.css
The issue was that our custom text splitting into multiple CardLines maintained a 20px gap between them. However, if a span within a CardLine contained text longer than the card text div, it wrapped onto a new line, and this extra line wasn't considered when calculating the spacing for the subsequent CardLines.
I've now set the line-height to initial. If you prefer a larger gap between lines, you can set it to 20px, for instance.
Before:
After:
> Fix: Spacing between card-text-line with auto-word-wrap

- .vscode/tasks.json
- build/integration/Jenkinsfile
- build/screenshots/Jenkinsfile
- integrations/standalone/package.json
- integrations/standalone/playwright.base.ts
- integrations/standalone/tests/integration/playwright.config.ts
- integrations/standalone/tests/mock/playwright.config.ts
- integrations/standalone/tests/screenshots/activities/interface.spec.ts
- integrations/standalone/tests/screenshots/playwright.config.ts
- integrations/standalone/vite.config.ts
- package.json
Seems to increase playwright tests speed about 30%. 
- only chrome: new ~5min, old ~8min
- all: new ~19min, old ~30min
This may be enough that the tests run more stable in the night, otherwise, I will invest further...
And we should also convert this repo to npm and streamline the commands :)
> Improve it tests

- packages/editor/src/components/parts/call/CallSelect.tsx
- packages/editor/src/components/parts/common/classification/ClassificationCombobox.tsx
- packages/editor/src/components/parts/common/exception-handler/ExceptionCombobox.tsx
- packages/editor/src/components/parts/process-data/ClassSelectorPart.tsx
- packages/editor/src/components/parts/rest/rest-request/rest-target/RestMethodSelect.tsx
- packages/editor/src/components/widgets/combobox/Combobox.css
I have now adapted the combobox accordingly. Additional information is now displayed greyed out behind the "Main-Part". However, if there is not enough space for the additional information, it appears on the second line again and the words are wrapped accordingly so that you never have to scroll to the right to see the entire content.
I deliberately chose not to scroll to the right here, as I have the feeling that scrolling in the open combobox may not be quite so pleasant. The only downside to this approach could be that if there is a lot of text in the info, you may again have the problem that the combobox dropdown becomes extremely long. What do you think? Is it more important to have everything on one line (a short dropdown) or see everything at once (multiple lines)?
> XIVY-14428 Improve Combobox design and responsivness

- packages/editor/src/components/parts/call/CallSelect.tsx
- packages/editor/src/components/parts/common/classification/ClassificationCombobox.tsx
- packages/editor/src/components/parts/common/exception-handler/ExceptionCombobox.tsx
- packages/editor/src/components/parts/process-data/ClassSelectorPart.tsx
- packages/editor/src/components/parts/rest/rest-request/rest-target/RestMethodSelect.tsx
- packages/editor/src/components/widgets/combobox/Combobox.css
The dialogue combo box is now structured as follows: 
MainDlg : start(data) - package name
Otherwise (following discussion from https://github.com/axonivy/inscription-client/pull/610) I have deactivated multiline-comboboxes. Everything is singleline and a tooltip is displayed on hover.
> XIVY-14428 Improvement for Combobox-Layout

- integrations/standalone/package.json
- integrations/standalone/src/mock/inscription-client-mock.ts
- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/App.tsx
- packages/editor/src/components/browser/Browser.tsx
- packages/editor/src/components/browser/role/AddRolePopover.tsx
- packages/editor/src/components/browser/role/RoleBrowser.tsx
- packages/editor/src/components/browser/role/validate-role.test.ts
- packages/editor/src/components/browser/role/validate-role.ts
- packages/editor/src/components/parts/common/responsible/useRoles.ts
- packages/editor/src/context/useFunction.ts
- packages/editor/src/query/query-client.ts
- packages/protocol/src/data/inscription.ts
- packages/protocol/src/inscription-protocol.ts
- playwright/tests/integration/mock/browser/browser-mock-utils.ts
- playwright/tests/integration/mock/browser/role.spec.ts
- playwright/tests/integration/mock/browser/tableCol.spec.ts
- playwright/tests/integration/mock/browser/type.spec.ts
My proposal for the AddRole functionality in the Type Browser (Core: https://github.com/axonivy/core/pull/7186). 
Certain validations are currently implemented directly in the frontend; it might make more sense to move these to the backend in the future?
Open To-Dos:
- Write tests
- Equip the CMS browser with the same query invalidation for the Add CMS functionality
- Later, I might try to have the newly added role automatically selected in a separate PR. What do you think of this feature?
> XIVY-14823 Add NewRole-Popover to RoleBrowser

- packages/editor/src/components/browser/Browser.tsx
- packages/editor/src/components/browser/BrowserBody.tsx
- packages/editor/src/components/browser/cms/CmsBrowser.test.tsx
- packages/editor/src/components/browser/cms/CmsBrowser.tsx
- packages/protocol/src/data/inscription.ts
- packages/protocol/src/inscription-protocol.ts
I would like to remove the refresh button from the CMS browser so that whenever a new CMS string is added via the SWT dialog, the data is refreshed automatically. I am using the same architecture as in the combine function in the data class editor for this.
> XIVY-14823 refactor newCmsString-Action to a function

- packages/editor/src/components/browser/role/AddRolePopover.tsx
- packages/editor/src/components/browser/role/RoleBrowser.tsx
To implement this auto-select feature, I had to use two useEffect hooks. Initially, I thought I could just change the selection in onSuccess, but it takes some time for the table to render with the new data. I could either use a setTimeout in onSuccess (not ideal) or use these useEffects to update the selection when a new role is detected. What do you think?
> XIVY-14823 Autoselect and expand newly added role

- packages/editor/src/components/browser/role/AddRolePopover.tsx
- packages/editor/src/components/browser/role/RoleBrowser.tsx
As you suggested, I reset the addedRoleName after the selection.
I have also changed the appearance of the Add Role button to ‘Primary’ and added the option to add the role directly with ‘Enter’ after you typed in a valid role name.
> XIVY-14823 Reset newRoleName on autoSelection & add role via enter
